---
name: test

"on":
  pull_request:
  push:

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: false

      - name: bootstrap
        run: script/bootstrap

      - name: test
        run: script/test
